on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-api:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './api'
        permissions: write-all
        steps:
          - name: 'Checkout'
            uses: actions/checkout@main

          - name: 'Login'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build'
            run: |
              docker build . --tag ghcr.io/blockarchitech/pebble_things_api:latest
              docker push ghcr.io/blockarchitech/pebble_things_api:latest
